name: "Docker merge"
description: "Docker merge"

inputs:
  registry:
    description: "Docker registry to which the images will be pushed."
    required: false
    default: ghcr.io
  name:
    description: "Name of the Docker image."
    required: true
  registry_username:
    description: "Username for image registry."
    required: false
    default: ${{ github.actor }}
  registry_token:
    description: "Token for image registry."
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  latest:
    description: "Set to true if this build should be used as the latest image. Defaults to auto. Set to either true, false or auto."
    required: false
    default: auto

runs:
  using: composite
  steps:
    - name: Download digests
      uses: actions/download-artifact@v3
      with:
        name: digests
        path: /tmp/digests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: name=${{ inputs.registry }}/${{ inputs.name }}
        flavor: | 
          latest=${{ inputs.latest }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha

    - name: Login to registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_token }}

    - name: Create manifest list and push
      shell: bash
      working-directory: /tmp/digests
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)         

    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}          